<?php
// pages/phone-fetcher.php
// Two modes:
// 1. JSON import — paste/upload JSON from local scraper
// 2. Manual quick-add — fill a form with key fields, admin fills rest later

$import_msg = '';
$preview    = null;
$answer_types = [0=>'N/A',1=>'Yes/No',2=>'Text',3=>'MCQ Single',4=>'MCQ Multiple',5=>'Date'];

// ── Load parameters for mapping ────────────────────────────────────────────────
$all_params = [];
try {
    $rows = $pdo->query('SELECT id, category, parameter FROM parameters WHERE type=1 ORDER BY category, sequence')->fetchAll();
    foreach ($rows as $r) {
        $all_params[$r['id']] = $r;
    }
} catch (Exception $e) {}

// Build a quick-lookup: lowercase parameter name → parameter id
$param_lookup = [];
foreach ($all_params as $id => $p) {
    $key = strtolower(trim($p['parameter']));
    $param_lookup[$key] = $id;
}

// ── GSMArena → parameter name mapping ─────────────────────────────────────────
// Key = GSMArena section.label (lowercase), Value = your parameter name (lowercase)
$gsmarena_map = [
    // Display
    'type'            => 'display type',
    'size'            => 'display size',
    'resolution'      => 'display resolution',
    'protection'      => 'display protection',
    'technology'      => 'display type',
    // Platform
    'os'              => 'os version',
    'chipset'         => 'processor version',
    'cpu'             => 'processor',
    'gpu'             => 'gpu',
    // Memory
    'internal'        => 'rom',
    'card slot'       => 'expandable storage',
    // Camera
    'triple'          => 'number of cameras',
    'quad'            => 'number of cameras',
    'single'          => 'number of cameras',
    'video'           => 'video quality',
    // Battery
    'capacity'        => 'battery capacity',
    'charging'        => 'fast charging',
    // Connectivity
    'wlan'            => 'wifi',
    'bluetooth'       => 'bluetooth',
    'gps'             => 'gps',
    'nfc'             => 'nfc',
    'usb'             => 'usb',
    // Body
    'weight'          => 'weight',
    'dimensions'      => 'dimensions',
    'build'           => 'body build',
    'sim'             => 'sim slots',
    // Launch
    'announced'       => 'launch date',
    'status'          => 'launch status',
];

function find_param_id(string $gsm_key, array $lookup, array $map): ?int {
    $lower = strtolower(trim($gsm_key));
    // Direct match
    if (isset($lookup[$lower])) return $lookup[$lower];
    // Via GSMArena map
    if (isset($map[$lower]) && isset($lookup[$map[$lower]])) return $lookup[$map[$lower]];
    // Partial match
    foreach ($lookup as $param_name => $id) {
        if (strpos($param_name, $lower) !== false || strpos($lower, $param_name) !== false) {
            return $id;
        }
    }
    return null;
}

// ── Handle JSON import preview ─────────────────────────────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['preview_json'])) {
    $json_str = trim($_POST['json_data'] ?? '');
    if (!$json_str && !empty($_FILES['json_file']['tmp_name'])) {
        $json_str = file_get_contents($_FILES['json_file']['tmp_name']);
    }
    if ($json_str) {
        $data = json_decode($json_str, true);
        if (!$data || !isset($data['name'])) {
            $import_msg = 'Invalid JSON. Make sure it was generated by the scraper.';
        } else {
            $preview = $data;
        }
    }
}

// ── Handle confirmed import ────────────────────────────────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['confirm_import'])) {
    $json_str = $_POST['json_payload'] ?? '';
    $data = json_decode($json_str, true);

    if ($data && isset($data['name'])) {
        // Check duplicate
        $exists = $pdo->prepare('SELECT id FROM product WHERE name = :n');
        $exists->execute([':n' => $data['name']]);
        $existing_id = $exists->fetchColumn();

        if ($existing_id) {
            $import_msg = '"' . htmlspecialchars($data['name']) . '" already exists (ID: ' . $existing_id . '). <a href="index.php?page=product-edit&id=' . $existing_id . '">Edit it →</a>';
        } else {
            $slug = strtolower(preg_replace('/[^a-z0-9]+/i', '-', $data['name']));
            $brand = trim($data['brand'] ?? '');
            $image = trim($data['image'] ?? '');

            $pdo->prepare(
                'INSERT INTO product (type,name,brand,slug,status,primary_image,primary_image_url,added,completion)
                 VALUES (1,:name,:brand,:slug,0,:img,:img,:img_time,0)'
            )->execute([':name'=>$data['name'],':brand'=>$brand,':slug'=>$slug,':img'=>$image,':img_time'=>date('Y-m-d H:i:s')]);
            $new_pid = $pdo->lastInsertId();

            // Import specs
            $mapped = 0; $unmapped = 0;
            $ins = $pdo->prepare(
                'INSERT INTO specs (product, question, answer, speculated, ts) VALUES (:pid, :q, :ans, 1, NOW())'
            );

            $specs_grouped = $data['specs'] ?? [];
            foreach ($specs_grouped as $section => $rows) {
                foreach ($rows as $row) {
                    $key = $row['key'] ?? '';
                    $val = $row['val'] ?? '';
                    if (!$key || !$val) continue;

                    $param_id = find_param_id($key, $param_lookup, $gsmarena_map);
                    if ($param_id) {
                        try {
                            $ins->execute([':pid'=>$new_pid,':q'=>$param_id,':ans'=>$val]);
                            $mapped++;
                        } catch (Exception $e) {}
                    } else {
                        $unmapped++;
                    }
                }
            }

            $import_msg = 'success:Imported <strong>' . htmlspecialchars($data['name']) . '</strong> (ID: ' . $new_pid . '). '
                . $mapped . ' specs mapped, ' . $unmapped . ' unmapped. '
                . '<a href="index.php?page=specs&id=' . $new_pid . '">Fill remaining specs →</a> · '
                . '<a href="index.php?page=product-edit&id=' . $new_pid . '">Edit product →</a>';
        }
    }
}

// ── Handle quick manual add ────────────────────────────────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['quick_add'])) {
    $name  = trim($_POST['name'] ?? '');
    $brand = trim($_POST['brand'] ?? '');
    $price = intval($_POST['launch_price_inr'] ?? 0);
    $image = trim($_POST['image'] ?? '');
    $release = trim($_POST['release_date'] ?? '');

    if ($name && $brand) {
        $slug = strtolower(preg_replace('/[^a-z0-9]+/i', '-', $name));
        try {
            $pdo->prepare(
                'INSERT INTO product (type,name,brand,slug,status,primary_image,primary_image_url,launch_price,launch_price_inr,release_date,added,completion)
                 VALUES (1,:name,:brand,:slug,0,:img,:img2,:price,:price2,:release,NOW(),0)'
            )->execute([
                ':name'    => $name,
                ':brand'   => $brand,
                ':slug'    => $slug,
                ':img'     => $image ?: '',
                ':img2'    => $image ?: '',
                ':price'   => $price ?: 0,
                ':price2'  => $price ?: null,
                ':release' => $release ?: null,
            ]);
            $new_pid = $pdo->lastInsertId();
            $import_msg = 'success:Created <strong>' . htmlspecialchars($name) . '</strong> as draft. '
                . '<a href="index.php?page=specs&id=' . $new_pid . '">Fill specs →</a>';
        } catch (PDOException $e) {
            $import_msg = 'Error: ' . $e->getMessage();
        }
    } else {
        $import_msg = 'Name and brand are required.';
    }
}

$is_success = str_starts_with($import_msg, 'success:');
$msg_text   = $is_success ? substr($import_msg, 8) : $import_msg;
?>

<?php if ($import_msg): ?>
<div class="alert <?= $is_success ? 'alert-success' : (str_starts_with($import_msg,'Error') ? 'alert-error' : 'alert-warn') ?>">
  <?= $msg_text ?>
</div>
<?php endif; ?>

<!-- ── How to section ──────────────────────────────────────────────────────── -->
<div class="alert alert-info mb-2">
  <div>
    <strong>GSMArena blocks server scraping.</strong>
    Use the local scraper on your Windows PC instead — it runs from your home IP and isn't blocked.
    Then paste the JSON output here to import.
  </div>
</div>


<!-- ── Bulk JSON Upload ────────────────────────────────────────────────────── -->
<div class="card" style="margin-bottom:1.5rem">
  <div class="card-header">
    <h2>📦 Bulk Import (multiple JSONs at once)</h2>
    <span class="text-xs text-muted">Upload all files from scraper output/ folder</span>
  </div>
  <div class="card-body">
    <p class="text-sm text-muted mb-2">
      After running the scraper, select all <code>.json</code> files from the <code>output/</code> folder
      and upload them here. All phones import in one shot.
    </p>
    <div id="bulk-drop-zone" style="
      border:2px dashed var(--cream-border);border-radius:var(--radius-lg);
      padding:2rem;text-align:center;cursor:pointer;transition:border-color .15s;
    ">
      <div style="font-size:2rem;margin-bottom:.5rem">📂</div>
      <div style="font-weight:600;margin-bottom:.35rem">Drop JSON files here</div>
      <div class="text-sm text-muted">or</div>
      <label class="btn btn-secondary btn-sm" style="margin-top:.75rem;cursor:pointer">
        Browse files
        <input type="file" id="bulk-file-input" multiple accept=".json" style="display:none">
      </label>
    </div>
    <div id="bulk-file-list" style="display:none;margin-top:1rem"></div>
    <div id="bulk-progress" style="display:none;margin-top:1rem">
      <div style="height:6px;background:var(--cream-border);border-radius:99px;overflow:hidden">
        <div id="bulk-progress-bar" style="height:100%;background:var(--purple);width:0%;transition:width .3s;border-radius:99px"></div>
      </div>
      <div id="bulk-status" class="text-sm text-muted" style="margin-top:.5rem"></div>
    </div>
    <div id="bulk-results" style="display:none;margin-top:1rem"></div>
    <button id="bulk-import-btn" class="btn btn-primary" style="margin-top:1rem;display:none">
      Import All
    </button>
  </div>
</div>

<div class="grid-2" style="gap:1.5rem;align-items:start;margin-bottom:1.5rem">

  <!-- ── Quick Manual Add ─────────────────────────────────────────────────── -->
  <div class="card">
    <div class="card-header">
      <h2>⚡ Quick Add Phone</h2>
      <span class="text-xs text-muted">Minimal info now, fill specs later</span>
    </div>
    <div class="card-body">
      <form method="POST" action="">
        <div class="form-row">
          <div class="field">
            <label>Phone Name *</label>
            <input type="text" name="name" required placeholder="e.g. Samsung Galaxy S25">
          </div>
          <div class="field">
            <label>Brand *</label>
            <input type="text" name="brand" required placeholder="e.g. Samsung">
          </div>
        </div>
        <div class="form-row">
          <div class="field">
            <label>Launch Price (₹)</label>
            <input type="number" name="launch_price_inr" placeholder="e.g. 79999">
          </div>
          <div class="field">
            <label>Release Date</label>
            <input type="date" name="release_date">
          </div>
        </div>
        <div class="field">
          <label>Image URL <span class="text-muted">(from GSMArena or manufacturer)</span></label>
          <input type="url" name="image" placeholder="https://fdn2.gsmarena.com/vv/pics/...">
        </div>
        <button type="submit" name="quick_add" class="btn btn-primary">Create Draft</button>
        <span class="field-hint" style="display:block;margin-top:.5rem">
          Creates a draft — go to Specs Editor to fill in details.
        </span>
      </form>
    </div>
  </div>

  <!-- ── JSON Import ──────────────────────────────────────────────────────── -->
  <div class="card">
    <div class="card-header">
      <h2>📥 Import from Scraper JSON</h2>
      <span class="text-xs text-muted">Run scraper locally, paste JSON here</span>
    </div>
    <div class="card-body">
      <?php if (!$preview): ?>
      <form method="POST" action="" enctype="multipart/form-data">
        <div class="field">
          <label>Paste JSON output from scraper</label>
          <textarea name="json_data" rows="10" class="mono"
                    placeholder='{"name":"OnePlus 13","brand":"OnePlus","image":"https://...","specs":{"Display":[...]}}'
                    style="font-size:.75rem"></textarea>
        </div>
        <div class="field" style="margin-bottom:0">
          <label>Or upload .json file</label>
          <input type="file" name="json_file" accept=".json">
        </div>
        <button type="submit" name="preview_json" class="btn btn-secondary" style="margin-top:1rem">
          Preview Import
        </button>
      </form>
      <?php else: ?>
      <!-- Preview mode -->
      <div style="margin-bottom:1rem">
        <div class="flex flex-center gap-1 mb-2">
          <?php if ($preview['image']): ?>
            <img src="<?= htmlspecialchars($preview['image']) ?>"
                 style="width:60px;height:80px;object-fit:contain;border-radius:8px;border:1px solid var(--cream-border)">
          <?php endif; ?>
          <div>
            <div style="font-weight:700;font-size:1.1rem"><?= htmlspecialchars($preview['name']) ?></div>
            <div style="color:var(--ink-light);font-size:.85rem"><?= htmlspecialchars($preview['brand'] ?? '') ?></div>
          </div>
        </div>

        <div class="alert alert-info" style="font-size:.8rem;margin-bottom:1rem">
          <?php
          $total_specs = 0; $will_map = 0; $wont_map = 0;
          foreach ($preview['specs'] ?? [] as $section => $rows) {
              foreach ($rows as $row) {
                  $total_specs++;
                  $pid = find_param_id($row['key'] ?? '', $param_lookup, $gsmarena_map);
                  if ($pid) $will_map++; else $wont_map++;
              }
          }
          ?>
          Found <strong><?= $total_specs ?></strong> specs.
          <strong style="color:var(--green)"><?= $will_map ?></strong> will auto-map to your parameters.
          <strong style="color:var(--amber)"><?= $wont_map ?></strong> won't map (fill manually after import).
        </div>

        <!-- Spec preview table -->
        <div style="max-height:280px;overflow-y:auto;border:1px solid var(--cream-border);border-radius:var(--radius);font-size:.78rem">
          <?php foreach ($preview['specs'] ?? [] as $section => $rows): ?>
          <div style="background:var(--purple-dim);padding:.3rem .75rem;font-weight:700;font-size:.7rem;color:var(--purple);text-transform:uppercase;letter-spacing:.05em">
            <?= htmlspecialchars($section) ?>
          </div>
          <?php foreach ($rows as $row):
            $pid = find_param_id($row['key'] ?? '', $param_lookup, $gsmarena_map);
          ?>
          <div style="display:flex;gap:.75rem;padding:.3rem .75rem;border-bottom:1px solid var(--cream-border);align-items:center">
            <span style="width:160px;flex-shrink:0;color:var(--ink-light)"><?= htmlspecialchars($row['key']) ?></span>
            <span style="flex:1;font-weight:500"><?= htmlspecialchars(mb_substr($row['val'],0,60)) ?></span>
            <?php if ($pid): ?>
              <span class="badge badge-green" style="flex-shrink:0">✓ maps</span>
            <?php else: ?>
              <span class="badge badge-gray" style="flex-shrink:0">manual</span>
            <?php endif; ?>
          </div>
          <?php endforeach; ?>
          <?php endforeach; ?>
        </div>

        <form method="POST" action="" style="margin-top:1rem;display:flex;gap:.75rem">
          <input type="hidden" name="json_payload" value="<?= htmlspecialchars(json_encode($preview)) ?>">
          <button type="submit" name="confirm_import" class="btn btn-primary">
            ✓ Confirm Import
          </button>
          <a href="index.php?page=phone-fetcher" class="btn btn-secondary">Cancel</a>
        </form>
      </div>
      <?php endif; ?>
    </div>
  </div>

</div>

<!-- ── Local scraper instructions ──────────────────────────────────────────── -->
<div class="card">
  <div class="card-header"><h2>🖥 Local Scraper Setup (Windows)</h2></div>
  <div class="card-body">
    <div class="grid-2" style="gap:2rem">
      <div>
        <p class="text-sm mb-2">The scraper runs on <strong>your PC</strong> — not blocked by GSMArena. One-time setup:</p>
        <ol style="font-size:.875rem;line-height:2;padding-left:1.25rem">
          <li>Download the <code>trustedspecs-scraper</code> folder</li>
          <li>Install Node.js from <a href="https://nodejs.org" target="_blank">nodejs.org</a> if not installed</li>
          <li>Open PowerShell in the scraper folder</li>
          <li>Run <code>node scraper.js help</code> to verify</li>
        </ol>
      </div>
      <div>
        <p class="text-sm mb-2"><strong>Common commands:</strong></p>
        <div style="background:var(--ink);color:#e8e6e0;padding:1rem;border-radius:var(--radius);font-family:var(--mono);font-size:.78rem;line-height:2">
          <div style="color:#a78bfa"># Search for a phone</div>
          <div>node scraper.js search "OnePlus 13"</div>
          <div style="margin-top:.5rem;color:#a78bfa"># Scrape by GSMArena URL</div>
          <div>node scraper.js url "https://gsmarena.com/oneplus_13-12345.php"</div>
          <div style="margin-top:.5rem;color:#a78bfa"># List upcoming phones</div>
          <div>node scraper.js upcoming</div>
        </div>
        <p class="text-sm mt-2 text-muted">
          Output saves as a <code>.json</code> file. Paste it in the import box above.
        </p>
      </div>
    </div>
  </div>
</div>

<!-- ── Other sources ────────────────────────────────────────────────────────── -->
<div class="card" style="margin-top:1.5rem">
  <div class="card-header"><h2>📡 Other Data Sources</h2></div>
  <div class="card-body">
    <div class="grid-3" style="gap:1rem">
      <div style="padding:1rem;background:var(--cream);border-radius:var(--radius-lg)">
        <div style="font-weight:700;margin-bottom:.35rem">RapidAPI — GSMArena API</div>
        <div class="text-sm text-muted" style="margin-bottom:.5rem">100 free calls/month. Structured JSON. ~$10/month for more.</div>
        <a href="https://rapidapi.com/search/gsmarena" target="_blank" class="btn btn-secondary btn-sm">View on RapidAPI ↗</a>
      </div>
      <div style="padding:1rem;background:var(--cream);border-radius:var(--radius-lg)">
        <div style="font-weight:700;margin-bottom:.35rem">Kimovil API</div>
        <div class="text-sm text-muted" style="margin-bottom:.5rem">Good Indian pricing data. Affordable plans.</div>
        <a href="https://www.kimovil.com/en/api" target="_blank" class="btn btn-secondary btn-sm">View Kimovil API ↗</a>
      </div>
      <div style="padding:1rem;background:var(--cream);border-radius:var(--radius-lg)">
        <div style="font-weight:700;margin-bottom:.35rem">FONOAPI</div>
        <div class="text-sm text-muted" style="margin-bottom:.5rem">Free phone spec API. Less comprehensive but free.</div>
        <a href="https://fonoapi.freshpixl.com" target="_blank" class="btn btn-secondary btn-sm">View FONOAPI ↗</a>
      </div>
    </div>
    <p class="text-sm text-muted" style="margin-top:1rem">
      Once you pick an API, I can build a direct integration that auto-imports specs without the local scraper step.
    </p>
  </div>
</div>
